### ISSUE TITLE
CentOS 7.6.1810 make run ERROR unsatisfiable constraints libffi-3.2.1-r6

### ISSUE THREAD

**Issue by guosyuan** [NetApp/eseries-perf-analyzer#8]
Hi All,

make run error message as below, need help

Step 6/15 : RUN apk add --update gcc musl-dev libffi-dev make openssl-dev
 ---> Running in 91a8e6215c0a
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libffi-3.2.1-r6:
    breaks: libffi-dev-3.3-r2[libffi=3.3-r2]
    satisfies: .python-rundeps-20200424.014659[so:libffi.so.6]
The command '/bin/sh -c apk add --update gcc musl-dev libffi-dev make openssl-dev' returned a non-zero code: 4
make: *** [build] Error 4

===Environmental information is as follows====
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[root@localhost ~]#
[root@localhost ~]# docker --version
Docker version 19.03.8, build afacb8b
[root@localhost ~]#
[root@localhost ~]# python --version
Python 2.7.5
[root@localhost ~]#

**Comment by lmprice** [comment]
@guosyuan I apologize for the long response. We discussed this bug, but I forgot to get back to you. I believe that the root of the issue is the fact that we have the edge repositories configured instead of the stable repos by default. We're going to submit a PR that will change this so that it is less likely to occur in the future.

A temporary fix is to change this in the build/alpine/repositories yourself or to comment out the line that runs the upgrade temporarily, as either one will prevent this from occuring.
